Efficiency module [13618]
eProsima/DDS-Router pull request #132
Opened 2022-01-26 14:27 UTC by jparisu

2022-01-27 08:59 UTC, jparisu commented
Tests are in their way, but the PR is already ready for review.

2022-02-01 14:03 UTC, rsanchez15 requested changes

2022-02-01 14:03 UTC, rsanchez15 commented on test/unittest/communication/payload_pool/MapPayloadPoolTest.cpp
> +class MockMapPayloadPool : public MapPayloadPool
Missing tests for `release` and `reserve` functions

2022-02-01 14:03 UTC, rsanchez15 commented on include/ddsrouter/communication/payload_pool/PayloadPool.hpp
> +    virtual bool release_(
Check that the `payload.data != nullptr ` to validate the output of the `empty()` function

2022-02-03 09:04 UTC, jparisu commented
Missing some comment or documentation in docs

2022-02-07 09:43 UTC, jparisu commented
Merge after PR: #140

2022-02-08 11:54 UTC, rsanchez15 requested changes

2022-02-08 11:54 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +
Remove this as the forthcoming version section is already included in parent file.

2022-02-08 11:54 UTC, rsanchez15 commented on include/ddsrouter/types/Data.hpp
> +// //! \c SerializedPayload_t to stream serializator
Remove zombie code

2022-02-08 11:54 UTC, rsanchez15 commented on src/cpp/types/Data.cpp
> +
Remove

2022-02-08 11:54 UTC, rsanchez15 commented on test/unittest/communication/payload_pool/MapPayloadPoolTest.cpp
> +// Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-02-08 11:54 UTC, rsanchez15 commented on test/unittest/communication/CMakeLists.txt
> +# Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
# Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-02-08 11:54 UTC, rsanchez15 commented on test/unittest/communication/payload_pool/CMakeLists.txt
> +# Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
# Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-02-08 11:54 UTC, rsanchez15 commented on test/unittest/communication/payload_pool/PayloadPoolTest.cpp
> +// Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2022 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2022-02-08 13:28 UTC, rsanchez15 approved these changes
LGTM 🚀

2022-02-08 13:28 UTC, merged