Support Dll for Windows
eProsima/DDS-Router pull request #157
Opened 2022-03-04 09:20 UTC by jparisu

After #152 

This PR adds Dll support for Windows library generation

2022-03-08 14:15 UTC, rsanchez15 requested changes

2022-03-09 09:46 UTC, jparisu commented on ddsrouter_core/cmake/test/cmake_test_utils.cmake
> +        target_compile_definitions(${TEST_EXECUTABLE_NAME} PRIVATE _CRT_DECLARE_NONSTDC_NAMES=0 ${SUBMODULE_PROJECT_MACROS}_SOURCE)
all these files are the same file. Modifying .common is enough

2022-03-10 08:49 UTC, rsanchez15 requested changes

2022-03-10 08:49 UTC, rsanchez15 commented on tools/ddsrouter_tool/project_settings.cmake
> +    $<$<BOOL:${WIN32}>:iphlpapi$<SEMICOLON>Shlwapi>
This is not required. Remove

2022-03-10 08:49 UTC, rsanchez15 commented on tools/ddsrouter_tool/test/application/CMakeLists.txt
> +    message(STATUS "Test Environment: ${TEST_ENVIRONMENT}")
Remove debug trace

2022-03-10 09:42 UTC, rsanchez15 approved these changes
LGTM 🚀

2022-03-10 09:43 UTC, merged