Activate communication test [14020]
eProsima/DDS-Router pull request #158
Opened 2022-03-05 10:30 UTC by jparisu

After #152

This PR reactivate the communication tests that were deactivated due to the refactor of YAML module.

2022-03-07 14:36 UTC, juanlofer-eprosima requested changes

2022-03-07 14:36 UTC, juanlofer-eprosima commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/WAN/DDSTestWAN.cpp
> +            5000
Remove

2022-03-07 14:36 UTC, juanlofer-eprosima commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/WAN/DDSTestWAN.cpp
> + * through UDPv4.
Update

2022-03-07 14:36 UTC, juanlofer-eprosima commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/WAN/DDSTestWAN.cpp
> +    // eprosima::ddsrouter::utils::Log::SetVerbosity(eprosima::ddsrouter::utils::Log::Kind::Info);
```suggestion
```

2022-03-08 09:40 UTC, jparisu commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/local/DDSTestLocal.cpp
>  constexpr const uint32_t DEFAULT_MESSAGE_SIZE = 1; // x50 bytes
I prefer them inside `test` namespace so they could not be used somewhere else by mistake (in general for test namespace)

2022-03-08 10:49 UTC, rsanchez15 requested changes

2022-03-08 10:49 UTC, rsanchez15 commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/WAN/DDSTestWAN.cpp
> +        bool client)
I'd create an enum with three options (SERVER, CLIENT, SERVER_AND_CLIENT) instead of using `bool`.

2022-03-08 10:49 UTC, rsanchez15 commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/WAN/DDSTestWAN.cpp
> +    DummyDDSPublisher<HelloWorld> publisher;
When I read `DummyDDSPublisher` I thought this was referring to the `Dummy` Participant. I'd avoid using the `Dummy` key word here. I think `TestPublisher` could be more adequate.

2022-03-10 10:36 UTC, rsanchez15 approved these changes

2022-03-10 10:37 UTC, merged