Internal documentation
eProsima/DDS-Router pull request #161
Opened 2022-03-09 09:41 UTC by jparisu

Internal documentation in Readme files to explain the directory structure and subpackages

2022-03-09 09:41 UTC, jparisu commented
Still in progress:

- [ ] ddsrouter_docs Documentation
- [ ] ddsrouter_yaml design explanation

2022-03-10 10:08 UTC, rsanchez15 requested changes

2022-03-10 10:08 UTC, rsanchez15 commented on .dev/scripts/README.md
> +This license must concordance with this one (change the year to the year the file has been created):
```suggestion
This license be consistent with the following one (change the year to the year the file has been created):
```

2022-03-11 08:04 UTC, rsanchez15 requested changes

2022-03-11 08:04 UTC, rsanchez15 commented on docs/README.md
> +commented separately and code is commented using Doxygen.
```suggestion
To learn about the repository structure, design decisions, development guidelines, etc., each package is documented separately and the source code is commented using Doxygen format.
```

2022-03-11 08:04 UTC, rsanchez15 commented on docs/README.md
> +In order to install this package independently, use the following command:
Missing information regarding the required Python packages.

2022-03-11 08:04 UTC, rsanchez15 commented on tools/ddsrouter_tool/README.md
> +This module create and executable that runs a DDS Router from a YAML configuration file.
```suggestion
This module create an executable that runs a DDS Router configured via *yaml* configuration file.
```

2022-03-11 08:04 UTC, rsanchez15 commented on tools/ddsrouter_tool/README.md
> +## Example of use
```suggestion
## Example of usage
```

2022-03-11 08:48 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +    To close the execution gracefully use SIGINT (C^) or SIGTERM (kill).
This is the text as it is printed from the tool

2022-03-11 10:29 UTC, rsanchez15 approved these changes

2022-03-11 10:56 UTC, merged