Yaml version support [14068]
eProsima/DDS-Router pull request #162
Opened 2022-03-10 09:00 UTC by jparisu

support different YAML versions regarding a yaml tag

2022-03-10 15:43 UTC, rsanchez15 requested changes

2022-03-10 15:43 UTC, rsanchez15 commented on ddsrouter_yaml/src/cpp/YamlReader.cpp
> +        const YamlReaderVersion /* Not Specialization */)
Remove the `/* Not Specialization */` comment as this is no longer a template. Instead use the following:

```suggestion
        const YamlReaderVersion /* version = LATEST */)
```

2022-03-11 07:56 UTC, jparisu commented on ddsrouter_core/src/cpp/types/dds/GuidPrefix.cpp
> +    : GuidPrefix(std::string(str_prefix))
It is not a cast, it is a `std::string` constructor

2022-03-11 08:11 UTC, jparisu commented on ddsrouter_yaml/include/ddsrouter_yaml/YamlReader.hpp
> + * TODO: Check if default arguments are needed. They may not be, as version should always be given
I removed it

2022-03-11 08:12 UTC, jparisu commented on ddsrouter_yaml/include/ddsrouter_yaml/yaml_configuration_tags.hpp
> +constexpr const char* VERSION_TAG_V_2_0("v2.0");    //! Version v2.0
We decided to leave it this way to avoid the yaml parse as a number

2022-03-11 10:27 UTC, merged