Collection Wait Handler Implementation
eProsima/DDS-Router pull request #205
Opened 2022-05-03 06:40 UTC by jparisu

After #203

2022-05-03 06:55 UTC, jparisu commented
This implementation requires to have a more specific classes for:
- Collections with internal thread safe methods (as DBQueue)
- Collections without internal thread safe methods (as std::queue)

- [ ] TODO

2022-05-06 09:08 UTC, juanlofer-eprosima requested changes

2022-05-06 09:08 UTC, juanlofer-eprosima commented on ddsrouter_event/test/unittest/wait/DBQueueWaitHandlerTest.cpp
> + * This test will not work as DBQueue do not allow moving values, it only copy them
```suggestion
 * This test will not work as DBQueue do not allow moving values, it only copies them
```

2022-05-06 09:08 UTC, juanlofer-eprosima commented on ddsrouter_event/test/unittest/wait/DBQueueWaitHandlerTest.cpp
> +    // They should be same object, check that modifying one modifies the other
```suggestion
    // They should be different objects, check that modifying one does not modify the other
```

2022-05-06 09:08 UTC, juanlofer-eprosima commented on ddsrouter_event/test/unittest/wait/DBQueueWaitHandlerTest.cpp
> +    {
```suggestion
    // 2
    {
```

2022-05-06 09:08 UTC, juanlofer-eprosima commented on ddsrouter_event/test/unittest/wait/DBQueueWaitHandlerTest.cpp
> +        std::this_thread::sleep_for(std::chrono::milliseconds(200));
Use time constant defined above?

2022-05-09 05:53 UTC, jparisu commented on ddsrouter_event/include/ddsrouter_event/wait/CollectionWaitHandler.hpp
> +     * This method will awake ONE thread waiting for data to be available if there is any waiting
We already studied this and in the future we will reimplement this class without CoutnerWaitHandler.
However, this comment references the behaviour of the method, not its implementation. Thus, it is true that will only awake a thread, while others will still be waiting in wait (after awaken and check the predicate is false).

2022-05-10 06:28 UTC, juanlofer-eprosima requested changes

2022-05-10 06:28 UTC, juanlofer-eprosima commented on ddsrouter_event/include/ddsrouter_event/wait/impl/ConsumerWaitHandler.ipp
> +    logDebug(DDSROUTER_WAIT_COLLECTION, "Created Consumer Wait Handler with type " << TYPE_NAME(T) << ".");
Update log catergory names.

2022-05-10 06:28 UTC, juanlofer-eprosima commented on ddsrouter_event/include/ddsrouter_event/wait/impl/DBQueueWaitHandler.ipp
> +    logDebug(DDSROUTER_WAIT_COLLECTION, "Moving element to DBQueue.");
Same here.

2022-05-10 06:28 UTC, juanlofer-eprosima commented on ddsrouter_event/test/unittest/wait/DBQueueWaitHandlerTest.cpp
> +TEST(DBQueueWaitHandlerTest, push_pop_one_thread_string_move)
This test might not do what is intended.

2022-05-11 06:28 UTC, juanlofer-eprosima approved these changes
LGTM

2022-05-11 06:46 UTC, merged