Refactor of Owner and Lessee ptrs [14325]
eProsima/DDS-Router pull request #231
Opened 2022-05-31 12:39 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2022-07-19 08:02 UTC, juanlofer-eprosima requested changes

2022-07-20 07:21 UTC, jparisu commented on ddsrouter_utils/include/ddsrouter_utils/memory/owner_ptr.hpp
> + *
`GuardedPtrData` is explained after LESSEE, line 45
`InternalPtrData` is not meant to be known neither used by the user, so the explanation must be in its own header

2022-07-20 07:22 UTC, jparisu commented on ddsrouter_utils/include/ddsrouter_utils/memory/impl/OwnerPtr.hpp
> + * But LesseePtr does not own the object, which could only be destroyed when no lessee is using it.
rephrased

2022-07-20 07:23 UTC, jparisu commented on ddsrouter_utils/include/ddsrouter_utils/exception/ValueAccessException.hpp
> + * @brief Exception thrown when not trying to reference a non valid value.
repeated

2022-07-20 07:38 UTC, juanlofer-eprosima approved these changes
LGTM

2022-07-20 12:54 UTC, merged