Change TLS to struct and add peer verification
eProsima/DDS-Router pull request #307
Opened 2022-09-19 10:30 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2022-09-19 14:35 UTC, rsanchez15 requested changes

2022-09-19 14:35 UTC, rsanchez15 commented on ddsrouter_yaml/src/cpp/YamlReader.cpp
> +void YamlReader::fill(
The client CA file should not be mandatory while the CA certificate of the server should not

2022-09-20 05:31 UTC, jparisu commented on ddsrouter_utils/include/ddsrouter_utils/macros/custom_enumeration.hpp
> +    inline const std::string& to_string(const enumeration_name& e)                                                           \
It is. It was an error that was not tested in custom enum tests (as it must be done by including 2 times the same header in different sources) and so it did not compile without it

2022-09-29 12:41 UTC, jparisu commented
Closed in favor of #311

2022-09-29 12:41 UTC, closed without merging