Add a blackbox repeater test
eProsima/DDS-Router pull request #336
Opened 2023-01-23 09:05 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2023-01-23 09:06 UTC, jparisu commented
This PR requires of https://github.com/eProsima/dev-utils/pull/35 to solve an ASAN problem

2023-01-26 10:42 UTC, irenebm commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/repeater/DDSTestRepeater.cpp
> +    // return std::make_shared<configuration::InitialPeersParticipantConfiguration>(
remove

2023-01-26 10:44 UTC, irenebm commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/repeater/DDSTestRepeater.cpp
> +    // test::LogChecker test_log_handler(Log::Kind::Error);
remove?

2023-02-02 07:37 UTC, rsanchez15 requested changes

2023-02-02 07:37 UTC, rsanchez15 commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/repeater/CMakeLists.txt
> +# Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
# Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2023-02-02 07:37 UTC, rsanchez15 commented on ddsrouter_core/test/blackbox/ddsrouter_core/dds/repeater/DDSTestRepeater.cpp
> +// Copyright 2021 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```suggestion
// Copyright 2023 Proyectos y Sistemas de Mantenimiento SL (eProsima).
```

2023-02-02 14:54 UTC, irenebm submitted a review, later dismissed

2023-02-02 14:57 UTC, rsanchez15 approved these changes

2023-02-02 15:57 UTC, merged