Fine tunning Configuration Module [12964]
eProsima/DDS-Router pull request #51
Opened 2021-11-19 11:41 UTC by jparisu

Adding comments, logs, delete functions, etc.

Merge after #50

2021-11-23 14:44 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @throw \c ConfigurationException in case the yaml inside blocklist is bad formed
```suggestion
     * @throw \c ConfigurationException in case the yaml inside blocklist is not well-formed
```

2021-11-23 14:45 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @brief Return a list with real topics in allowedlist in the configuration
```suggestion
     * @brief Return a set with the real topics included in allowedlist
```

2021-11-23 14:47 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     */
change

2021-11-23 14:49 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @todo: This method will dissapear once the dynamic module is implemented
```suggestion
     * @todo: This method will disappear once the dynamic module is implemented
```

2021-11-23 14:49 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @return List of real topics
```suggestion
     * @return Set of real topics
```

2021-11-23 14:50 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * This method collects the same functionality that share \c allowlist and \c blacklist
```suggestion
     * This method collects the same functionality that share \c allowlist and \c blocklist
```

2021-11-23 14:50 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @param [in] list_tag: name of the tag to look the list in the configuration
```suggestion
     * @param [in] list_tag: tag name of the list to look for in the configuration
```

2021-11-23 14:51 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> + * Each Participant that require specific configuration must inherite from this class.
```suggestion
 * Each Participant that requires specific configuration must inherit from this class.
```

2021-11-23 14:52 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> +     * @brief Construct an invald configuration
```suggestion
     * @brief Construct an invalid configuration
```

2021-11-23 14:53 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> +     * The type is get in construction. If the type is not valid, it will cause an exception.
```suggestion
     * The type is set in construction. If the type is not valid, it will cause an exception.
```

2021-11-23 14:54 UTC, juanlofer-eprosima commented on src/cpp/configuration/Configuration.cpp
> +            logWarning(DDSROUTER_CONFIGURATION, "Fail to create participant configuration " << id_str
```suggestion
            logWarning(DDSROUTER_CONFIGURATION, "Failed to create participant configuration " << id_str
```

2021-11-24 06:37 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> + * This class joins every DDSRouter Configuration characteristic and give methods to interact with this configuration.
:+1:

2021-11-24 06:37 UTC, jparisu commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> + * This class joins every DDSRouter Participant Configuration characteristic and give methods to interact with it.
Somehow it sounds familiar to me

2021-11-24 06:38 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     *  map or an empty yaml, it cannot be otherwise.
:+1:

2021-11-24 06:38 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @throw \c ConfigurationException in case the yaml is not well formed or is not a map or empty
:+1:

2021-11-24 06:39 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * This method get the allowedlist in configuration and get only those topics that can actually
:+1:

2021-11-24 06:39 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @throw \c ConfigurationException in case the yaml inside allowedlist is bad formed
:+1:

2021-11-24 06:40 UTC, jparisu commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> +     * @throw \c ConfigurationException in case the type could not be correctly set by yaml or id or yaml is bad formed
:+1:

2021-11-24 06:40 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @brief Return a list with topics in allowedlist in the configuration
:+1:

2021-11-24 06:41 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @brief Return a list with topics in blocklist in the configuration
:+1:

2021-11-24 06:41 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @throw \c ConfigurationException in case the yaml inside allowedlist is bad formed
:+1:

2021-11-24 06:41 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @throw \c ConfigurationException in case the yaml inside blocklist is bad formed
:+1:

2021-11-24 06:42 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @brief Return a list with real topics in allowedlist in the configuration
:+1:

2021-11-24 06:45 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     */
:+1:

2021-11-24 06:46 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @todo: This method will dissapear once the dynamic module is implemented
:+1:

2021-11-24 06:47 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @return List of real topics
:+1:

2021-11-24 06:47 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * This method collects the same functionality that share \c allowlist and \c blacklist
:+1:

2021-11-24 06:48 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @param [in] list_tag: name of the tag to look the list in the configuration
:+1:

2021-11-24 06:49 UTC, jparisu commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> + * Each Participant that require specific configuration must inherite from this class.
:+1:

2021-11-24 06:50 UTC, jparisu commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> +     * @brief Construct an invald configuration
:+1:

2021-11-24 06:50 UTC, jparisu commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> +     * The type is get in construction. If the type is not valid, it will cause an exception.
:+1:

2021-11-24 06:50 UTC, jparisu commented on src/cpp/configuration/Configuration.cpp
> +            logWarning(DDSROUTER_CONFIGURATION, "Fail to create participant configuration " << id_str
:+1:

2021-11-24 07:16 UTC, juanlofer-eprosima requested changes

2021-11-24 07:16 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * is created and added to the return list.
```suggestion
     * is created and added to the list to be returned.
```

2021-11-24 07:16 UTC, juanlofer-eprosima commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @param [in] list_tag: tag name of the lust to look for in the configuration
```suggestion
     * @param [in] list_tag: tag name of the list to look for in the configuration
```

2021-11-24 07:17 UTC, jparisu commented on include/ddsrouter/configuration/ParticipantConfiguration.hpp
> + * This class joins every DDSRouter Participant Configuration characteristic and give methods to interact with it.
:+1:

2021-11-24 07:18 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * is created and added to the return list.
:+1:

2021-11-24 07:18 UTC, jparisu commented on include/ddsrouter/configuration/Configuration.hpp
> +     * @param [in] list_tag: tag name of the lust to look for in the configuration
:+1:

2021-11-24 07:33 UTC, juanlofer-eprosima approved these changes
LGTM

2021-11-24 07:43 UTC, merged