Guid Prefix Implementation
eProsima/DDS-Router pull request #61
Opened 2021-11-26 13:26 UTC by jparisu

base in branch #58

2021-11-30 14:25 UTC, juanlofer-eprosima requested changes
Please fix uncrustify test and remove windows warnings.

2021-11-30 14:25 UTC, juanlofer-eprosima commented on src/cpp/types/endpoint/GuidPrefix.cpp
> +    // TODO : make available to modify for the whole guid prefix, so is not truncted to 255
```suggestion
    // TODO : make available to modify for the whole guid prefix, so it is not truncated to 255
```

2021-11-30 14:25 UTC, juanlofer-eprosima commented on src/cpp/types/endpoint/GuidPrefix.cpp
> + * To be valid, the GuidPrefix and the EntityId must not be invalid / unknown
```suggestion
 * To be valid, the \c GuidPrefix and the \c EntityId must not be invalid / unknown
```

2021-12-01 08:23 UTC, jparisu commented on include/ddsrouter/types/endpoint/GuidPrefix.hpp
> + * This class does not belong to class Guid due to a monumental error in OOP (parallel hierarchy is the future).
:+1:

2021-12-01 08:24 UTC, jparisu commented on src/cpp/types/endpoint/GuidPrefix.cpp
> +const char* GuidPrefix::ROS_DISCOVERY_SERVER_GUID_PREFIX_STR_("44.53.00.5f.45.50.52.4f.53.49.4d.41");
:+1:

2021-12-01 08:25 UTC, jparisu commented on src/cpp/types/endpoint/GuidPrefix.cpp
> +        std::stringstream ss(ROS_DISCOVERY_SERVER_GUID_PREFIX_STR_);
:+1:

2021-12-01 08:25 UTC, jparisu commented on include/ddsrouter/types/endpoint/GuidPrefix.hpp
> +     * @param id number to seed for the final GUID [Default: 0]
:+1:

2021-12-01 08:26 UTC, jparisu commented on include/ddsrouter/types/endpoint/GuidPrefix.hpp
> +     * @param ros : whether use the Discovery Server ROS2 specific guid [Default: false]
:+1:

2021-12-01 08:27 UTC, jparisu commented on src/cpp/types/endpoint/GuidPrefix.cpp
> + * To be valid, the GuidPrefix and the EntityId must not be invalid / unknown
:+1:

2021-12-01 09:15 UTC, juanlofer-eprosima approved these changes
LGTM

2021-12-01 09:15 UTC, merged