Local Discovery Server Implementation [13026]
eProsima/DDS-Router pull request #65
Opened 2021-11-29 10:27 UTC by jparisu

Over branch #64

2021-12-09 11:25 UTC, rsanchez15 requested changes
Pending testing on #75

2021-12-09 11:57 UTC, jparisu commented on src/cpp/configuration/WANParticipantConfiguration.cpp
> +const TransportProtocol WANParticipantConfiguration::DEFAULT_TRANSPORT_PROTOCOL_ =
These are two different things.
1. WAN should ALWAYS have same default transport protocol as any other Discovery Server?
2. WAN should NOW have UDP or TCP?

I would leave it as it is but changing the default value to UDP

2021-12-09 13:21 UTC, jparisu commented on include/ddsrouter/configuration/DiscoveryServerRTPSParticipantConfiguration.hpp
> + * Each Participant that require specific configuration must inherit from this class.
:+1:

2021-12-09 13:22 UTC, jparisu commented on include/ddsrouter/participant/implementations/rtps/impl/CommonRTPSRouterParticipant.ipp
> +// }
Add it as std method in case specific attributes are not needed

2021-12-10 06:42 UTC, jparisu commented
This PR will be included in  #75

2021-12-10 06:42 UTC, closed without merging