Add Participant documentation
eProsima/DDS-Router pull request #74
Opened 2021-12-02 13:48 UTC by jparisu

Add glossary
Add Participant Documentation
Add Participant Echo Documentation

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-12-02 15:12 UTC, rsanchez15 requested changes

2021-12-02 15:12 UTC, rsanchez15 commented on docs/rst/user_manual/glossary.rst
> +        Each Topic is uniquely identified by a topic name and a topic type name (name of the data it transmits).
```suggestion
        Each Topic is uniquely identified by a topic name and a topic type name (name of the data type it transmits).
```

2021-12-02 15:12 UTC, rsanchez15 commented on docs/rst/user_manual/glossary.rst
> +        DDS element that publish data in a specific Topic.
```suggestion
        DDS entity that publish data in a specific Topic.
```

2021-12-02 15:12 UTC, rsanchez15 commented on docs/rst/user_manual/glossary.rst
> +        See `Fast DDS documentation <https://fast-dds.docs.eprosima.com/en/v2.4.0/fastdds/dds_layer/subscriber/subscriber.html>`__
```suggestion
        See `Fast DDS documentation <https://fast-dds.docs.eprosima.com/en/v2.4.1/fastdds/dds_layer/subscriber/subscriber.html>`__
```

2021-12-02 15:27 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +:term:`Participant` is an abstraction over the :term:`DomainParticipant`.
:+1:

2021-12-02 15:28 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +This entity manages the discovery over a specific network or interface.
:+1:

2021-12-02 15:29 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +the :term:`Participant`.
:+1:

2021-12-02 15:34 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +terms how the :term:`Participant` behaves.
:+1:

2021-12-02 15:36 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +In order to create a :term:`Participant` of a specific type, use `type` tag in yaml, or set the :term:`Participant Id`
:+1:

2021-12-02 15:36 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +These are examples of :term:`Participant` configurations:
:+1:

2021-12-02 15:38 UTC, jparisu commented on docs/rst/user_manual/participants/participant.rst
> +These are the different :term:`Participant Types<Participant Type>` available.
:+1:

2021-12-02 15:41 UTC, jparisu commented on docs/rst/user_manual/participants/echo.rst
> +DDS Router Echo Participant
:+1:

2021-12-02 15:42 UTC, jparisu commented on docs/rst/user_manual/participants/echo.rst
> +and write by an **Echo Participant**:
:+1:

2021-12-02 15:42 UTC, jparisu commented on docs/rst/user_manual/glossary.rst
> +.. _glossary:
:+1:

2021-12-02 15:43 UTC, jparisu commented on docs/rst/user_manual/glossary.rst
> +        be exactly a DomainParticipant, it may be the case that is several or none DomainParticipants.
:+1:

2021-12-02 15:44 UTC, jparisu commented on docs/rst/user_manual/glossary.rst
> +        Unique identifier of a Participant. It is implemented as a `string`,
:+1:

2021-12-02 15:44 UTC, jparisu commented on docs/rst/user_manual/glossary.rst
> +        DDS element that manages the discovery between Endpoints.
:+1:

2021-12-02 15:45 UTC, jparisu commented on docs/rst/user_manual/glossary.rst
> +        See `Fast DDS documentation <https://fast-dds.docs.eprosima.com/en/v2.4.0/fastdds/dds_layer/topic/topic.html>`__
:+1:

2021-12-02 15:46 UTC, jparisu commented on docs/rst/user_manual/glossary.rst
> +        See `Fast DDS documentation <https://fast-dds.docs.eprosima.com/en/v2.4.0/fastdds/dds_layer/domain/domainParticipant/domainParticipant.html>`__
:+1:

2021-12-03 08:26 UTC, rsanchez15 approved these changes

2021-12-03 08:26 UTC, merged