Added dds communication blackbox test
eProsima/DDS-Router pull request #80
Opened 2021-12-13 14:31 UTC by juanlofer-eprosima

Signed-off-by: Juan López Fernández <juanlopez@eprosima.com>

2021-12-14 08:41 UTC, rsanchez15 requested changes

2021-12-14 08:41 UTC, rsanchez15 commented on test/CMakeLists.txt
> +# [TEST_EXTRA_HEADERS] -> a sixth optional argument with extra headers needed for the test
```suggestion
# ARGV5 -> extra headers needed for the test (sixth optional argument)
```

2021-12-14 08:41 UTC, rsanchez15 commented on test/blackbox/CMakeLists.txt
> +# [TEST_EXTRA_HEADERS] -> a fifth optional argument with extra headers needed for the test
```suggestion
# ARGV4 -> extra headers needed for the test (fifth optional argument)
```

2021-12-14 08:41 UTC, rsanchez15 commented on test/blackbox/ddsrouter_core/resources/dds_test_simple_configuration.yaml
> +# This .yaml contains the configuration for the complex test.
```suggestion
# This YAML configures the DDS Router for the DDS communication test.
```

2021-12-14 08:41 UTC, rsanchez15 commented on test/blackbox/ddsrouter_core/resources/dds_test_simple_configuration.yaml
> +# It is composed of two simple (RTPS) participants.
```suggestion
# It is composed of two Simple Participants.
```

2021-12-14 08:47 UTC, juanlofer-eprosima commented on test/CMakeLists.txt
> +# [TEST_EXTRA_HEADERS] -> a sixth optional argument with extra headers needed for the test
:+1:

2021-12-14 08:48 UTC, juanlofer-eprosima commented on test/blackbox/CMakeLists.txt
> +# [TEST_EXTRA_HEADERS] -> a fifth optional argument with extra headers needed for the test
:+1:

2021-12-14 08:48 UTC, juanlofer-eprosima commented on test/blackbox/ddsrouter_core/resources/dds_test_simple_configuration.yaml
> +# This .yaml contains the configuration for the complex test.
:+1:

2021-12-14 08:49 UTC, juanlofer-eprosima commented on test/blackbox/ddsrouter_core/resources/dds_test_simple_configuration.yaml
> +# It is composed of two simple (RTPS) participants.
:+1:

2021-12-14 15:37 UTC, rsanchez15 submitted a review, later dismissed
Approved considering that this will be refactored in order to be compatible with any DDS user participant (SIMPLE, CLIENT, SUPERCLIENT and SERVER)

2021-12-15 10:18 UTC, rsanchez15 approved these changes

2021-12-15 10:19 UTC, merged