User interface documentation [13243]
eProsima/DDS-Router pull request #81
Opened 2021-12-14 09:13 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-12-15 13:24 UTC, juanlofer-eprosima requested changes

2021-12-16 07:10 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +The |ddsrouter| is an application that is executed from command line.
:+1:

2021-12-16 07:11 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +The |ddsrouter| depends on Fast DDS ``fastrtps`` and ``fastcdr`` libraries.
:+1:

2021-12-16 07:11 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +In order to correctly execute the Router, be sure that ``fastrtps`` and ``fastcdr`` are sourced.
:+1:

2021-12-16 07:16 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +    If Fast DDS has been installed in the system, these libraries would be sourced by default.
:+1:

2021-12-16 07:18 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +
:+1:

2021-12-16 07:19 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +It shows the Manual information for the application.
:+1:

2021-12-16 07:21 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +For this argument to work, the |ddsrouter| must have been compiled in ``debug`` CMake build type, or compiled with
:+1:

2021-12-16 07:22 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +default name ``DDS_ROUTER_CONFIGURATION.yaml`` that must be in the directory where the application has been executed.
:+1:

2021-12-16 07:22 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +file name in the current directory, the application will fail.
:+1:

2021-12-16 07:23 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +The topics that the |ddsrouter| is routing could be changed in run time.
:+1:

2021-12-16 07:24 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +Including topics in ``allowedlist`` in the configuration will create new :term:`Writers <DataWriter>` and
:+1:

2021-12-16 07:24 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +A File Watcher is a process that runs in background and watch the |ddsrouter| configuration file.
:+1:

2021-12-16 07:25 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +and interact with the |ddsrouter| in order to reload the topics.
:+1:

2021-12-16 07:25 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +The configuration file will be automatically reloaded with the period set.
:+1:

2021-12-16 07:55 UTC, juanlofer-eprosima commented on docs/rst/developer_manual/installation/configuration/cmake_options.rst
> +        - CMake optimization build type
```suggestion
        - CMake optimization build type.
```

2021-12-16 07:55 UTC, juanlofer-eprosima commented on docs/rst/user_manual/user_interface.rst
> +The |eddsrouter| is an application executed from command line.
```suggestion
|eddsrouter| is an application executed from command line.
```

2021-12-16 07:55 UTC, juanlofer-eprosima commented on docs/rst/user_manual/user_interface.rst
> +The |eddsrouter| depends on |fastdds| ``fastrtps`` and ``fastcdr`` libraries.
```suggestion
|eddsrouter| depends on |fastdds| ``fastrtps`` and ``fastcdr`` libraries.
```

2021-12-16 07:55 UTC, juanlofer-eprosima commented on docs/rst/user_manual/user_interface.rst
> +    If Fast DDS has been installed in the system, these libraries would be sourced by default.
Note still not visible

2021-12-16 08:13 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +The |eddsrouter| is an application executed from command line.
:+1:

2021-12-16 08:15 UTC, jparisu commented on docs/rst/user_manual/user_interface.rst
> +    If Fast DDS has been installed in the system, these libraries would be sourced by default.
true :cry:

2021-12-16 08:20 UTC, juanlofer-eprosima approved these changes
LGTM

2021-12-16 08:49 UTC, merged