Fix PeriodicHandler error
eProsima/DDS-Router pull request #86
Opened 2021-12-14 15:03 UTC by jparisu

Fix error in PeriodicHandler so it does not call callback if it has finished.
When reload period is too small, it provokes a segfault because calls DDSRouter when it has been destroyed.

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-12-15 14:50 UTC, juanlofer-eprosima requested changes

2021-12-16 13:18 UTC, jparisu commented on include/ddsrouter/event/EventHandler.hpp
> +     * it destroy the object.
Old file version

2021-12-16 13:20 UTC, juanlofer-eprosima requested changes

2021-12-16 13:23 UTC, juanlofer-eprosima requested changes

2021-12-16 13:23 UTC, juanlofer-eprosima commented on include/ddsrouter/event/impl/EventHandler.ipp
> +        logWarning(DDSROUTER_HANDLER, "Unsetting callback from an EventHandler that had yet no callback set.")
```suggestion
        logWarning(DDSROUTER_HANDLER, "Unsetting callback from an EventHandler that had no callback set.")
```

2021-12-16 13:24 UTC, jparisu commented on include/ddsrouter/event/EventHandler.hpp
> +}         /* namespace ddsrouter */
:+1:  (weird this change did pass the uncrustify)

2021-12-16 13:25 UTC, jparisu commented on include/ddsrouter/event/EventHandler.hpp
> +    //! Mutex to block EventHandler execution while lambda is being set or called
:+1:

2021-12-16 13:26 UTC, jparisu commented on src/cpp/main.cpp
> +        std::cout << file_path << std::endl;
My fault

2021-12-16 13:26 UTC, jparisu commented on include/ddsrouter/event/impl/EventHandler.ipp
> +            // Setting callback
:+1:

2021-12-16 13:27 UTC, jparisu commented on include/ddsrouter/event/impl/EventHandler.ipp
> +
:+1:

2021-12-16 13:28 UTC, jparisu commented on include/ddsrouter/event/impl/EventHandler.ipp
> +    // Return true if the condition has been fulfilled. It could stop due to a unset callback
:+1:

2021-12-16 13:28 UTC, jparisu commented on include/ddsrouter/event/impl/EventHandler.ipp
> +        logWarning(DDSROUTER_HANDLER, "Unsetting callback from an EventHandler that had yet no callback set.")
:+1:

2021-12-16 14:15 UTC, juanlofer-eprosima approved these changes
LGTM

2021-12-16 14:15 UTC, merged