Release notes
eProsima/DDS-Router pull request #91
Opened 2021-12-16 07:00 UTC by jparisu

Signed-off-by: jparisu <javierparis@eprosima.com>

2021-12-17 13:07 UTC, rsanchez15 requested changes

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +with the |ddsrouter|, the different DDS configurations that the application is able to reproduce, etc.
```suggestion
This release includes several **features** regarding the routing of DDS data, the |ddsrouter| configuration, the user interaction
with the |ddsrouter|, and the different DDS configurations that the application is able to reproduce.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Allow to execute application with a *YAML* configuration file.
```suggestion
* Allow to execute the application with a *YAML* configuration file.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support initial topics in allowlist.
```suggestion
* Support for initial topics in allowlist.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support block topic filters.
```suggestion
* Support for block topic filters.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support to route Topics specified in allowlist regarding Topic name and Topic Type name.
```suggestion
* Support for routing Topics specified in allowlist regarding Topic name and Topic Type name.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support connect to new Topics in run time (by reloading configuration).
```suggestion
* Support for connecting to new Topics in run-time (by reloading configuration).
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support disabling a Topic in run time.
```suggestion
* Support for disabling a Topic in run-time.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Support enabling a Topic that has been disabled in run time.
```suggestion
* Support for enabling a Topic that has been disabled in run-time.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Data types agnostic.
```suggestion
* Agnostic to topic data types.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* Using Fast DDS RTPS layer for discovery, publication and subscription.
```suggestion
* Using *eProsima Fast DDS* RTPS layer for discovery, publication and subscription.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* **ROS 2 Discovery Server Example**, to connect a simple DDS with Discovery Server using ROS 2 configuration.
```suggestion
* **ROS 2 Discovery Server Example**, to connect a regular DDS network with a Discovery Server network using ROS 2 configuration.
```

2021-12-17 13:07 UTC, rsanchez15 commented on docs/rst/notes/notes.rst
> +* This Documentation.
```suggestion
* This same documentation.
```

2021-12-20 07:06 UTC, jparisu commented on docs/rst/notes/notes.rst
>  Version v0.0.0
:+1:

2021-12-20 07:08 UTC, jparisu commented on docs/rst/notes/notes.rst
> +with the |ddsrouter|, the different DDS configurations that the application is able to reproduce, etc.
:+1:

2021-12-20 07:09 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* Support connect to new Topics in run time (by reloading configuration).
:+1:

2021-12-20 07:09 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* Support enabling a Topic that has been disabled in run time.
:+1:

2021-12-20 07:09 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* Data types agnostic.
:+1:

2021-12-20 07:11 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* Using Fast DDS RTPS layer for discovery, publication and subscription.
:+1:

2021-12-20 07:11 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* **ROS 2 Discovery Server Example**, to connect a simple DDS with Discovery Server using ROS 2 configuration.
:+1:

2021-12-20 07:12 UTC, jparisu commented on docs/rst/notes/notes.rst
> +* This Documentation.
:+1:

2021-12-21 13:58 UTC, rsanchez15 approved these changes
LGTM

2021-12-21 13:58 UTC, merged